version: "3.9"
services:
  app:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.app
    ports:
      - "${APP_PORT-8501}:8501"
    env_file:
      - ../.env
    depends_on:
      - qdrant
    volumes:
      - ../data:/app/data
      - ../reports:/app/reports

  qdrant:
    image: qdrant/qdrant:v1.8.4
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  # Optional: Postgres for feedback + Grafana/Prometheus can be added later
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interview_coach
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
volumes:
  qdrant_storage:
  pgdata:
