apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-datasource
    access: proxy
    url: postgres:5432
    database: interview_coach
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true
    isDefault: true